"""empty message

Revision ID: 43d6d40cb4e7
Revises: 
Create Date: 2018-10-25 10:28:01.386579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d6d40cb4e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_parent'), 'node', ['parent'], unique=False)
    op.create_index(op.f('ix_node_text'), 'node', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_text'), table_name='node')
    op.drop_index(op.f('ix_node_parent'), table_name='node')
    op.drop_table('node')
    # ### end Alembic commands ###
